---
applications:
- name: getting-started-nodejs
#      buildpack: https://github.com/cloudfoundry/nodejs-buildpack.git
  docker:
    image: mrllus2cbacr.azurecr.io/dealworks/getting-started-nodejs/cloudbee:latest  
    username: mrllus2cbacr
  memory: 1GB
  instances: 1
  timeout: 180
  host: getting-started-nodejs
#  stack: cflinuxfs3
  # services:
  #   - test-nodejs
    