---
applications:
- name: getting-started-nodejs
  disk_quota: 1G
  docker:
    image: mrllus2cbacr.azurecr.io/dealworks/getting-started-nodejs/cloudbee:latest
    username: mrllus2cbacr
  health-check-type: process
  instances: 1
  memory: 1G
  routes:
  - route: getting-started-nodejs.apps.us2.devg.foundry.mrll.com
  stack: cflinuxfs3
  timeout: 180
  
